projects:
  app:
    #   schemaPath: src/schema.graphql
    includes: ['packages/app/src/**/*.graphql']
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    #   schemaPath: src/generated/db.graphql
    includes: ['packages/server/src/**/*.graphql']
    extensions:
      codegen:
        - generator: graphql-binding
          language: typescript
          output:
            binding: src/types/gql.ts
